# Generated by Django 3.2.13 on 2022-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('telefono_emergencia', models.IntegerField(verbose_name='Telefono de Emergencia')),
                ('email', models.EmailField(max_length=30, null=True, verbose_name='Email')),
                ('Fecha_Comienzo', models.DateTimeField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_emergencia', models.CharField(max_length=20, verbose_name='Tel-emerg')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('registro', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('cuota', models.DecimalField(decimal_places=2, default=1900.0, max_digits=6, verbose_name='Cuota')),
                ('aldia', models.CharField(choices=[('No', 'NO'), ('Si', 'SI')], default='no', max_length=17, verbose_name='Cuota al dia?')),
                ('estado', models.CharField(choices=[('No activo', 'No activo'), ('Activo', 'Activo')], default='No activo', max_length=10, verbose_name='Estado')),
                ('genero', models.CharField(blank=True, default='femenino', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socio',
                'ordering': ['id'],
            },
        ),
    ]
